### ISSUE TITLE
How to unset bookmark

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#13]
Ich habe schon wieder vergessen, wie man das macht! ;-)

(Nebenbei, manchmal bringe ich es nicht fertig, die Progressbar anzeigen zu lassen bevor nicht ein Bookmark gesetzt wurde.)

**Comment by mLorin** [comment]
Es ist nicht mehr möglich das lesezeichen zu löschen (muss man das können?)

2. ist warscheindlich ein bug, sehe es mir noch an

**Comment by sarahfrederickx** [comment]
Ich mache diese Question zu. Thx. Nein, man muss das Bookmark nicht (unbedingt) löschen können, und das andere ist komisches Verhalten, das ich nicht reproduzieren kann. Schauen wir später.
