### ISSUE TITLE
Chapters only from the first part are shown

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#14]
If there are more than one part, chapters are not shown in the progress bar.
Example: https://eskript.ethz.ch/videosinteaching/
![screen shot 2017-08-29 at 17 04 09](https://user-images.githubusercontent.com/9086977/29828530-4122bf34-8cdd-11e7-8fff-18a28c2ab47c.png)

**Comment by mLorin** [comment]
Normally the parts are ignored and only the chapters counted, need to check why this book doesn't work

**Comment by mLorin** [comment]
The last update was fast pushed to escript...?
There could be a lot more bugs

**Comment by sarahfrederickx** [comment]
We will find out! ;-) easy.
And I've seen the behaviour, stopping before the second part, in other books.
In any case, we should always test with new books because I've seen older books behave strangely also with other new functionalities we've implemented.

**Comment by mLorin** [comment]
Newer Books nummerate the chapters in each part continuously.
script now accounts for that
