### ISSUE TITLE
Learning Progress Settings Page

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#16]
Wahrscheinlich zu früh, aber dass es nicht vergessen geht:

A) Bei 'recalculate' (falls leere Kapitel?)
Warning: DOMDocument::loadHTML(): Empty string supplied as input in /instances/home/mskript/htdocs/wp-content/plugins/prog/includes/functions.php on line 55
1
Warning: Cannot modify header information - headers already sent by (output started at /instances/home/mskript/htdocs/wp-content/plugins/prog/includes/functions.php:55) in /instances/home/mskript/htdocs/wp-content/plugins/prog/admin/class-prog-admin.php on line 161

B) Wenn man
- Show lecture progress
- Display chapter length
anklickt/-wählt und 'Save all changes' klickt, dann werden 'Settings saved' aber beide Optionen sind nicht mehr angewählt.

(Beispiel: https://mskript.ethz.ch/bonemultiscale/wp-admin/options-general.php?page=prog)

**Comment by mLorin** [comment]
Empty string problem solved

**Comment by mLorin** [comment]
removed unused options
