### ISSUE TITLE
No show of colored bars if bookmark not set on heading

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#2]
If bookmark is only set on a chapter (not a heading), progress bar doesn't show the colored bars on main page.
![both-set-on-chapter](https://user-images.githubusercontent.com/9086977/28358230-66ea9dde-6c6e-11e7-9016-8765739c5434.png)
![green-set-on-heading-yellow-set-on-chapter](https://user-images.githubusercontent.com/9086977/28358234-6cf7b36a-6c6e-11e7-8207-3d1eb358d071.png)

**Comment by mLorin** [comment]
bookmark needs to be re-saved
