### ISSUE TITLE
Number of formulas

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#4]
Also calculate and show number of formulas (as additional material on main page)

**Comment by sarahfrederickx** [comment]
How do you calculate the formulas?
Most formulas are in shortcodes: [latex]...[/latex]

**Comment by mLorin** [comment]
formulas are calculated by counting: $$............$$
i found in most books the formulas are saved like this

**Comment by mLorin** [comment]
[latex] formeln werden nun auch gezählt
