### ISSUE TITLE
Green progress doesn't show if further than lecture bookmark

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#7]
Green progress bar doesn't show if it is further than yellow lecture bookmark.
![green-progress-further-than-yellow](https://user-images.githubusercontent.com/9086977/28359425-6e803e2e-6c72-11e7-9436-bfc68c04aa17.png)

**Comment by mLorin** [comment]
in this case it was because the bookmark was on a chapter and not subchapter.
Because of the structure of the book i have currently problems to calculate the position if it's not set to an subchapter

**Comment by sarahfrederickx** [comment]
Yep, you're right, I wanted to check but forgot.
