### ISSUE TITLE
Highlighting Feature

### ISSUE THREAD

**Issue by sarahfrederickx** [mLorin/LearningProgress#8]
Funktion: User kann Text highlighten und Highlights wieder entfernen.
Beachte: Sollte neben hypothes.is funktionieren und auch auf mobilen Geräten funktionieren!

Hier ist das Repo (mit highlighting.js) des UZH-Programmierers:
[https://github.com/elreydelblueray/ebook_highlighting_commenting_feature_for_eskript](url)

Im highlighting.js oberen ReadMe Teil lesen.

**Comment by mLorin** [comment]
Moving Highlighting Feature to different Plugin

**Comment by mLorin** [comment]
https://github.com/mLorin/highlight-and-comment-Pressbook-Plugin
